kind: pipeline
name: default

steps:
  - name: build
    image: docker
    volumes:
      - name: docker-sock
        path: /var/run/host.sock
    environment:
      DOCKER_PASSWORD:
        from_secret: DOCKER_PUBLIC_PASSWORD
      DOCKER_USER:
        from_secret: DOCKER_PUBLIC_USER
    commands:
      - export DOCKER_HOST=unix://var/run/host.sock
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD harbor.dsrd.libraries.psu.edu
      - docker build -t harbor.dsrd.libraries.psu.edu/public/chef-lint:$DRONE_BUILD_NUMBER .
      - docker tag harbor.dsrd.libraries.psu.edu/public/chef-lint:$DRONE_BUILD_NUMBER harbor.dsrd.libraries.psu.edu/public/chef-lint:latest
      - docker push harbor.dsrd.libraries.psu.edu/public/chef-lint
    when:
      branch:
        - master

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock